<a href="https://colab.research.google.com/github/okubobarros/simplilearn_ds_python/blob/main/Data_Science_With_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
first_numpy_array = np.array([1,2,3,4])

In [ ]:
print(first_numpy_array)

[1 2 3 4]


In [ ]:
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# empty  function is used to created a new array of given shape and type 
array_with_empty = np.empty((2,3))
array_with_empty

array([[3.11455347e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#reshape
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(1,6,5)
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [ ]:
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
TwoD_array = oneD_array.reshape(3,5)
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
ThreeD_array = np.arange(27).reshape(3,3,3)
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#PANDAS

- Powerful data structure
- Fast and efficient data wrangling
- Easy data aggregation and transformation
- Tools for reading / writing data
- Intelligent and automated data alignment
- High performance merging and joining of data sets

Four main libraries of Pandas data structure are:
- Series
- Data Frame: is a two-dimensional labeled data structure with columns of potentially different data types
- Panel
- Panel 4D

In [ ]:
df_faa_dataset = pd.read_csv('/faa_ai_prelim.csv')

In [ ]:
df_faa_dataset.shape

(83, 42)

In [ ]:
df_faa_dataset.head()

UPDATED ENTRY_DATE EVENT_LCL_DATE EVENT_LCL_TIME LOC_CITY_NAME  \
0      No  19-FEB-16      19-FEB-16      00:45:00Z    MARSHVILLE   
1      No  19-FEB-16      18-FEB-16      23:55:00Z     TAVERNIER   
2      No  19-FEB-16      18-FEB-16      22:14:00Z       TRENTON   
3      No  19-FEB-16      18-FEB-16      17:10:00Z     ASHEVILLE   
4      No  19-FEB-16      18-FEB-16      00:26:00Z     TALKEETNA   

   LOC_STATE_NAME LOC_CNTRY_NAME  \
0  North Carolina            NaN   
1         Florida            NaN   
2      New Jersey            NaN   
3  North Carolina            NaN   
4          Alaska            NaN   

                                            RMK_TEXT EVENT_TYPE_DESC  \
0  AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...        Accident   
1  AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...        Incident   
2  AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...        Incident   
3  AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...        Incident   
4  AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...        Incident   

                  FSDO_DESC  ... PAX_INJ_NONE PAX_INJ_MINOR PAX_INJ_SERIOUS  \
0     FAA Charlotte FSDO-68  ...          NaN           NaN             NaN   
1         FAA Miami FSDO-19  ...          NaN           NaN             NaN   
2  FAA Philadelphia FSDO-17  ...          NaN           NaN             NaN   
3     FAA Charlotte FSDO-68  ...          NaN           NaN             NaN   
4     FAA Anchorage FSDO-03  ...          NaN           1.0             NaN   

  PAX_INJ_FATAL PAX_INJ_UNK  GRND_INJ_NONE GRND_INJ_MINOR GRND_INJ_SERIOUS  \
0           NaN         NaN            NaN            NaN              NaN   
1           NaN         NaN            NaN            NaN              NaN   
2           NaN         NaN            NaN            NaN              NaN   
3           NaN         NaN            NaN            NaN              NaN   
4           NaN         NaN            NaN            NaN              NaN   

  GRND_INJ_FATAL  GRND_INJ_UNK  
0            NaN           NaN  
1            NaN           NaN  
2            NaN           NaN  
3            NaN           NaN  
4            NaN           NaN  

[5 rows x 42 columns]

In [ ]:
#view all the columns present in the dataset
df_faa_dataset.columns

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

In [ ]:
#create a new data frame with only required columns
df_analyse_dataset = df_faa_dataset[['ACFT_MAKE_NAME','LOC_STATE_NAME','ACFT_MODEL_NAME','RMK_TEXT','FLT_PHASE','EVENT_TYPE_DESC','FATAL_FLAG']]

In [ ]:
#view the type of the object
type(df_analyse_dataset)

pandas.core.frame.DataFrame

In [ ]:
#view first five observations
df_analyse_dataset.head()

ACFT_MAKE_NAME  LOC_STATE_NAME ACFT_MODEL_NAME  \
0          BEECH  North Carolina              36   
1           VANS         Florida             RV7   
2         CESSNA      New Jersey             172   
3        LANCAIR  North Carolina             235   
4         CESSNA          Alaska             172   

                                            RMK_TEXT       FLT_PHASE  \
0  AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...   UNKNOWN (UNK)   
1  AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...   LANDING (LDG)   
2  AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...  APPROACH (APR)   
3  AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...   LANDING (LDG)   
4  AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...   LANDING (LDG)   

  EVENT_TYPE_DESC FATAL_FLAG  
0        Accident        Yes  
1        Incident        NaN  
2        Incident        NaN  
3        Incident        NaN  
4        Incident        NaN

In [ ]:
#replace all NaN for Fatal flag with 'No'
df_analyse_dataset['FATAL_FLAG'].fillna(value='No', inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [ ]:
df_analyse_dataset.head()

ACFT_MAKE_NAME  LOC_STATE_NAME ACFT_MODEL_NAME  \
0          BEECH  North Carolina              36   
1           VANS         Florida             RV7   
2         CESSNA      New Jersey             172   
3        LANCAIR  North Carolina             235   
4         CESSNA          Alaska             172   

                                            RMK_TEXT       FLT_PHASE  \
0  AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...   UNKNOWN (UNK)   
1  AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...   LANDING (LDG)   
2  AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...  APPROACH (APR)   
3  AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...   LANDING (LDG)   
4  AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...   LANDING (LDG)   

  EVENT_TYPE_DESC FATAL_FLAG  
0        Accident        Yes  
1        Incident         No  
2        Incident         No  
3        Incident         No  
4        Incident         No

In [ ]:
#view the shape of the dataset
df_analyse_dataset.shape

(83, 7)

In [ ]:
#drop values whre ACFT_MAKE_NAME (aircraft make name) is not avaiable
df_final_dataset = df_analyse_dataset.dropna(subset=['ACFT_MAKE_NAME'])

In [ ]:
#now view the new shape of the dataset
df_final_dataset.shape

(78, 7)

In [ ]:
#group by aircraft name
aircraftType = df_final_dataset.groupby('ACFT_MAKE_NAME')

In [ ]:
#view them by aircraft using size method
aircraftType.size()

ACFT_MAKE_NAME
AERO COMMANDER             1
AERONCA                    1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
BEECH                      9
BELL                       2
BOEING                     3
CESSNA                    23
CHAMPION                   2
CHRISTEN                   1
CONSOLIDATED VULTEE        1
EMBRAER                    1
ENSTROM                    1
FAIRCHILD                  1
FLIGHT DESIGN              1
GLOBE                      1
GREAT LAKES                1
GRUMMAN                    1
GULFSTREAM                 1
HUGHES                     1
LANCAIR                    2
MAULE                      1
MOONEY                     4
NORTH AMERICAN             1
PIPER                     10
PITTS                      1
SAAB                       1
SABRELINER                 1
SOCATA                     2
VANS                       1
dtype: int64

In [ ]:
#now group the dataset by fatal flag
fatalAccidents = df_final_dataset.groupby('FATAL_FLAG')

In [ ]:
#view the fatal accidents size
fatalAccidents.size()

FATAL_FLAG
No     71
Yes     7
dtype: int64

In [ ]:
#select the accidents with fatality with fatal flag yes
accidents_with_fatality = fatalAccidents.get_group('Yes')

In [ ]:
#view the accidents with fatality
accidents_with_fatality

ACFT_MAKE_NAME  LOC_STATE_NAME ACFT_MODEL_NAME  \
0            BEECH  North Carolina              36   
53           PIPER         Florida            PA28   
55   FLIGHT DESIGN      California            CTLS   
79  NORTH AMERICAN         Arizona             F51   
80        CHAMPION      California           8KCAB   
81           BEECH      California              35   
82          CESSNA         Alabama             182   

                                             RMK_TEXT      FLT_PHASE  \
0   AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...  UNKNOWN (UNK)   
53  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...  UNKNOWN (UNK)   
55  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...  UNKNOWN (UNK)   
79  AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...  UNKNOWN (UNK)   
80  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...  UNKNOWN (UNK)   
81  N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...  UNKNOWN (UNK)   
82  N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...  UNKNOWN (UNK)   

   EVENT_TYPE_DESC FATAL_FLAG  
0         Accident        Yes  
53        Accident        Yes  
55        Accident        Yes  
79        Accident        Yes  
80        Accident        Yes  
81        Accident        Yes  
82        Accident        Yes

#Pandas part2

In [ ]:
#import libraries
#read data from csv

In [ ]:
df_fdny_csv_data_raw = pd.read_csv('/FDNY_Firehouse_Listing.csv')

In [ ]:
#view the content of data
df_fdny_csv_data_raw.describe

<bound method NDFrame.describe of                                           FacilityName  \
0                                   Engine 4/Ladder 15   
1                                             Engine 6   
2    Manhattan Borough Command/Battalion 1/Engine 7...   
3                                             Ladder 8   
4                                    Engine 9/Ladder 6   
..                                                 ...   
214                               Engine 167/Ladder 87   
215                               Engine 164/Ladder 84   
216                               Engine 151/Ladder 76   
217                                         Engine 168   
218                                           Marine 9   

              FacilityAddress        Borough  Postcode   Latitude  Longitude  \
0             42 South Street      Manhattan     10005  40.703694 -74.007717   
1           49 Beekman Street      Manhattan     10038  40.709971 -74.005395   
2            100 Duane Street

In [ ]:
df_fdny_csv_data_raw.head()

FacilityName     FacilityAddress  \
0                                 Engine 4/Ladder 15     42 South Street   
1                                           Engine 6   49 Beekman Street   
2  Manhattan Borough Command/Battalion 1/Engine 7...    100 Duane Street   
3                                           Ladder 8  14 N. Moore Street   
4                                  Engine 9/Ladder 6     75 Canal Street   

     Borough  Postcode   Latitude  Longitude  Community Board  \
0  Manhattan     10005  40.703694 -74.007717              101   
1  Manhattan     10038  40.709971 -74.005395              101   
2  Manhattan     10007  40.715339 -74.006300              101   
3  Manhattan     10013  40.719574 -74.006620              101   
4  Manhattan     10002  40.715408 -73.992834              103   

   Community Council   Census Tract      BIN         BBL  \
0                   1             7  1000867  1000350001   
1                   1          1501  1001287  1000930030   
2                   1            33  1001647  1001500025   
3                   1            33  1002150  1001890035   
4                   1            16  1003898  1003000030   

                                      NTA  
0       Battery Park City-Lower Manhattan  
1       Battery Park City-Lower Manhattan  
2  SoHo-TriBeCa-Civic Center-Little Italy  
3  SoHo-TriBeCa-Civic Center-Little Italy  
4                               Chinatown

In [ ]:
#view data statistics using describe()
df_fdny_csv_data_raw.describe()

Postcode    Latitude   Longitude  Community Board  \
count    219.000000  219.000000  219.000000       219.000000   
mean   10791.237443   40.719515  -73.936757       289.251142   
std      556.084887    0.083305    0.093270       127.027975   
min    10001.000000   40.512739  -74.238950       101.000000   
25%    10304.500000   40.664492  -73.985509       203.000000   
50%    11105.000000   40.715339  -73.937195       306.000000   
75%    11232.500000   40.774003  -73.886618       405.000000   
max    11695.000000   40.893028  -73.716081       503.000000   

       Community Council    Census Tract           BIN           BBL  
count          219.000000     219.000000  2.190000e+02  2.190000e+02  
mean            25.575342    5808.223744  2.914454e+06  2.859184e+09  
std             15.579554   19319.590290  1.303650e+06  1.281276e+09  
min              1.000000       1.000000  1.000867e+06  1.000350e+09  
25%             12.000000     127.000000  2.006944e+06  2.026125e+09  
50%             26.000000     278.000000  3.070506e+06  3.024650e+09  
75%             38.000000     812.000000  4.084528e+06  4.029700e+09  
max             51.000000  157902.000000  5.169276e+06  5.080400e+09

In [ ]:
#view columns of the dataset
df_fdny_csv_data_raw.columns

Index(['FacilityName', 'FacilityAddress', 'Borough', 'Postcode', 'Latitude',
       'Longitude', 'Community Board', 'Community Council ', 'Census Tract',
       'BIN', 'BBL', 'NTA'],
      dtype='object')

In [ ]:
#view index of dataset
df_fdny_csv_data_raw.index

RangeIndex(start=0, stop=219, step=1)

In [ ]:
#count number of records
df_fdny_csv_data_raw.count()

FacilityName          219
FacilityAddress       219
Borough               219
Postcode              219
Latitude              219
Longitude             219
Community Board       219
Community Council     219
Census Tract          219
BIN                   219
BBL                   219
NTA                   219
dtype: int64

In [ ]:
#view datatypes
df_fdny_csv_data_raw.dtypes

FacilityName           object
FacilityAddress        object
Borough                object
Postcode                int64
Latitude              float64
Longitude             float64
Community Board         int64
Community Council       int64
Census Tract            int64
BIN                     int64
BBL                     int64
NTA                    object
dtype: object

In [ ]:
#select FDNY information boroughwise
groupby_borough = df_fdny_csv_data_raw.groupby('Borough')

In [ ]:
#view FDNY information for each borough
groupby_borough.size()

Borough
Bronx            34
Brooklyn         66
Manhattan        48
Queens           51
Staten Island    20
dtype: int64

In [ ]:
#select FDNY information for Manhattan
fdny_info_Manhattan = groupby_borough.get_group('Manhattan')

In [ ]:
#view FDNY information for Manhattan
fdny_info_Manhattan

FacilityName  \
0                                  Engine 4/Ladder 15   
1                                            Engine 6   
2   Manhattan Borough Command/Battalion 1/Engine 7...   
3                                            Ladder 8   
4                                   Engine 9/Ladder 6   
5                     Battalion 4/Engine 15/Ladder 18   
6                                 Engine 28/Ladder 11   
7                                            Engine 5   
8                                Division 1/Ladder 20   
9                                  Engine 33/Ladder 9   
10                               Battalion 6/Ladder 3   
11                                           Squad 18   
12                                Engine 34/Ladder 21   
13                                          Engine 26   
14                     Battalion 7/Engine 3/Ladder 12   
15                                 Engine 1/Ladder 24   
16                                          Engine 14   
17                                 Engine 16/Ladder 7   
18                                          Engine 21   
19                     Battalion 9/Engine 54/Ladder 4   
20                                          Engine 23   
21                                Engine 40/Ladder 35   
22                               Division 3/Ladder 25   
23                                          Engine 74   
24                      Battalion 8/Engine 8/Ladder 2   
25                                          Engine 44   
26                   Battalion 10/Engine 22/Ladder 13   
27                                Engine 58/Ladder 26   
28                                Engine 53/Ladder 43   
29                                          Engine 91   
30                   Battalion 12/Engine 35/Ladder 14   
31                   Battalion 11/Engine 76/Ladder 22   
32                                          Engine 47   
33                                Engine 59/Ladder 30   
34                                Engine 37/Ladder 40   
35                                Engine 84/Ladder 34   
36                                Engine 95/Ladder 36   
37                                          Engine 55   
38                                           Rescue 1   
39                                Engine 39/Ladder 16   
40                   Battalion 16/Engine 69/Ladder 28   
41                                Engine 80/Ladder 23   
42                   Battalion 13/Engine 93/Ladder 45   
43                                Engine 10/Ladder 10   
44                                          Engine 65   
45                     Battalion 2/Engine 24/Ladder 5   
46                                          Engine 67   
47                                           Marine 1   

              FacilityAddress    Borough  Postcode   Latitude  Longitude  \
0             42 South Street  Manhattan     10005  40.703694 -74.007717   
1           49 Beekman Street  Manhattan     10038  40.709971 -74.005395   
2            100 Duane Street  Manhattan     10007  40.715339 -74.006300   
3          14 N. Moore Street  Manhattan     10013  40.719574 -74.006620   
4             75 Canal Street  Manhattan     10002  40.715408 -73.992834   
5              25 Pitt Street  Manhattan     10002  40.716439 -73.983927   
6           222 East 2 Street  Manhattan     10009  40.721879 -73.982526   
7          340 East 14 Street  Manhattan     10003  40.731494 -73.983407   
8        253 Lafayette Street  Manhattan     10012  40.723026 -73.996571   
9       42 Great Jones Street  Manhattan     10012  40.726986 -73.992526   
10         108 East 13 Street  Manhattan     10003  40.733093 -73.989443   
11         132 West 10 Street  Manhattan     10014  40.734518 -74.000381   
12       440 West 38th Street  Manhattan     10018  40.756593 -73.996471   
13         220 West 37 Street  Manhattan     10018  40.753107 -73.990376   
14         150 West 19 Street  Manhattan     10011  40.741196 -73.996868   
15         142 West 31 Street  

#Matplolib

In [ ]:
#Matplolib
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Data from Ohio state, leading causes of death in the state from year 2012
#cause of deaths
cause = 'Chronic Diseases','Unintentional Injuries','Alzheimers','Influenza and Pneumonia','Sepsis','Others'
percentile = [62,5,4,2,1,26]


In [ ]:
# set the pie chart plot properties

# set figure size
plt.figure(figsize=(10,10))
#explode the largest pie in the data set
explode = (0.05,0,0,0,0)
#set pie chart properties
plt.pie(percentile, labels=cause,explode,autopct='%1.1f%%', startangle=70)
#set axis equal to draw pie as circle
plt.axis('equal')
#set title of the pie chart
plt.title('Ohio State - 2012 : Leading Causes of Death')
#show the plot (pie chart)
plt.show()

#**SciPy**

Is an extension of Numpy for scientific and advanced mathematical algorithms and functions.

In [ ]:
#import required libraries
import numpy as np
from scipy import linalg

In [ ]:
#Test has 30 questions and worth 150 marks
#True and false questions worth 4 marks each
#multiple choice questions worth 9 points each

#let x is the number of true/false questions
#let y is the number of multiple choice questions

# (x + y = 30)
# (4x + 9y = 150)
testQuestionVariable = np.array([1,1],[4,9])
testQuestionValue = np.array([30,150])


In [ ]:
#use linalg function of Scipy
#use solve method to solve the linear equation and find value for x and y
linalg.solve(testQuestionVariable, testQuestionValue)

#Scikit learn

Scikit is a powerful and modern machine learning Python libray for fully and semi-automated data analysis and information extraction.

- Create separate objects for feature and response.
- Ensure that features and response have only numeric values.
- Features and response should be in the form of a Numpy ndarray.
- Since features and response would be in the form of arrays, they would have shapes and sizes.
- Features are always mapped as x and response is mapped as y.